splash screen implementation
julian-mainardis-globant/movies-app pull request #3
Opened 2022-10-11 16:58 UTC by AndresConfortiGL

## Description
The app starts with a Splash screen with a little animation using Lottie.

## Story Type
- New feature :white_check_mark:
- Change request
- Bug fix
- Tech

## How Can This Be Tested?
By opening the app you will be prompted with an splash screen made with a Lottie animation.

## Evidences
| Pixel 3 | Nexus S |
| ------------- | ------------- |
|![pixel (online-video-cutter com)](https://user-images.githubusercontent.com/109096226/195671781-e6a86213-f054-459c-ba2b-4e5b5c735bef.gif)|![nexus (online-video-cutter com)](https://user-images.githubusercontent.com/109096226/195671873-d813b59a-0eee-4496-b3cc-782baee82d18.gif)|

| Coverage Test  |
| ------------- |
|![coverage](https://user-images.githubusercontent.com/109096226/195150106-4d353f1e-a73a-4314-ba13-c6c390be25fb.png)|

## Checklist
- All unit Test passed :white_check_mark:

## Tested on
The project was tested on the following devices:
- Pixel 3 API 27 - Android 8.1
- Nexus S API 30 - Android 11

## Package Structure
| Structure |
| ------------- |
|![image](https://user-images.githubusercontent.com/109096226/195381634-d67f21a1-bc6c-448a-9a5f-3a4d22bd2397.png)|

2022-10-12 21:04 UTC, kearneyeduardo approved these changes

2022-10-13 14:53 UTC, jnicolaslaurenti approved these changes

2022-10-13 14:57 UTC, mariano98montero requested changes

2022-10-13 14:57 UTC, mariano98montero commented on app/src/main/res/layout/splash_screen.xml
> +        android:layout_height="match_parent"
please use wrap_content here instead of match

2022-10-13 15:08 UTC, AndresConfortiGL commented on app/src/main/res/layout/splash_screen.xml
> +        android:layout_height="match_parent"
done

2022-10-13 15:58 UTC, mariano98montero approved these changes

2022-10-13 18:03 UTC, DiegoDiazGlobant approved these changes

2022-10-13 18:04 UTC, merged